### ISSUE TITLE
test fails while adding Power support(ppc64le) with continuous integration/testing 

### ISSUE THREAD

**Issue by asellappen** [daneads/pycallgraph2#23]
$ make tests
py.test \
	--pep8 \
	--ignore=pycallgraph2/memory_profiler.py \
	test pycallgraph2 examples
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.16/bin/py.test", line 10, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python2.7.16/lib/python2.7/site-packages/_pytest/config/__init__.py", line 61, in main
    config = _prepareconfig(args, plugins)
  File "/home/travis/virtualenv/python2.7.16/lib/python2.7/site-packages/_pytest/config/__init__.py", line 196, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/travis/virtualenv/python2.7.16/lib/python2.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/travis/virtualenv/python2.7.16/lib/python2.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/virtualenv/python2.7.16/lib/python2.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/travis/virtualenv/python2.7.16/lib/python2.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/travis/virtualenv/python2.7.16/lib/python2.7/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/travis/virtualenv/python2.7.16/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/home/travis/virtualenv/python2.7.16/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/travis/virtualenv/python2.7.16/lib/python2.7/site-packages/_pytest/config/__init__.py", line 655, in pytest_cmdline_parse
    self.parse(args)
  File "/home/travis/virtualenv/python2.7.16/lib/python2.7/site-packages/_pytest/config/__init__.py", line 871, in parse
    self._preparse(args, addopts=addopts)
  File "/home/travis/virtualenv/python2.7.16/lib/python2.7/site-packages/_pytest/config/__init__.py", line 817, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/travis/virtualenv/python2.7.16/lib/python2.7/site-packages/pluggy/manager.py", line 280, in load_setuptools_entrypoints
    message="Plugin %r could not be loaded: %s!" % (ep.name, e),
pluggy.manager.PluginValidationError: Plugin 'pytest_cov' could not be loaded: (pytest 4.3.0 (/home/travis/virtualenv/python2.7.16/lib/python2.7/site-packages), Requirement.parse('pytest>=4.6'))!
make: *** [tests] Error 1
Makefile:21: recipe for target 'tests' failed
The command "make tests" exited with 2.

**Comment by asellappen** [comment]
Is this active travis?.
did you get a chance to look at this issue,Pls update.
