### ISSUE TITLE
failed when tested with ‘import torch’

### ISSUE THREAD

**Issue by SeekPoint** [daneads/pycallgraph2#36]
PS C:\yk_repo\yk_coding\pycallgraph2> python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>>

=====the pytorch is fine！！！！！

then I run:

from pycallgraph2 import PyCallGraph
from pycallgraph2.output import GraphvizOutput

with PyCallGraph(output=GraphvizOutput()):
    #code to profile
    import torch
    '''  tested with pytorch 2.0.0 and 1.13.1
    PS C:\yk_repo\yk_coding\pycallgraph2> python .\demo_pcg2.py
C:\Python310\lib\site-packages\torch\distributed\distributed_c10d.py:283: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn(
Traceback (most recent call last):
  File "C:\yk_repo\yk_coding\pycallgraph2\demo_pcg2.py", line 6, in <module>
    import torch
  File "C:\Python310\lib\site-packages\torch\__init__.py", line 1187, in <module>
    from .functional import *  # noqa: F403
  File "C:\Python310\lib\site-packages\torch\functional.py", line 8, in <module>
    import torch.nn.functional as F
  File "C:\Python310\lib\site-packages\torch\nn\__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "C:\Python310\lib\site-packages\torch\nn\modules\__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear, LazyLinear
  File "C:\Python310\lib\site-packages\torch\nn\modules\linear.py", line 7, in <module>
    from .. import functional as F
  File "C:\Python310\lib\site-packages\torch\nn\functional.py", line 1437, in <module>
    _VF.threshold_,
  File "C:\Python310\lib\site-packages\torch\_VF.py", line 26, in __getattr__
    def __getattr__(self, attr):
  File "C:\Python310\lib\site-packages\pycallgraph2\tracer.py", line 25, in tracer
    self.processor.process(frame, event, self.memory())
  File "C:\Python310\lib\site-packages\pycallgraph2\tracer.py", line 171, in process
    module_path = module.__file__
  File "C:\Python310\lib\site-packages\torch\_VF.py", line 27, in __getattr__
    return getattr(self.vf, attr)
AttributeError: 'torch._C._VariableFunctionsClass' object has no attribute '__file__'
     '''

**Comment by mitchellsayer** [comment]
@SeekPoint Were you able to solve this?

**Comment by christian-oleary** [comment]
Same issue on Windows 11 with Python 3.9.19 using:

- pycallgraph2==1.1.3
- torch==2.1.0
- torchaudio==2.1.0
